# Generated by Django 5.0 on 2023-12-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='genre',
        ),
    ]
