# Generated by Django 5.0 on 2023-12-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_category_genre_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cover colors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Formats',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='number_of_pages',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='cover_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.covercolor'),
        ),
        migrations.AddField(
            model_name='item',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.format'),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.language'),
        ),
    ]
