# Generated by Django 5.0 on 2023-12-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_covercolor_format_language_item_number_of_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='language',
        ),
    ]
