# Generated by Django 5.0 on 2023-12-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cover_color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='format',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_of_pages',
        ),
    ]
