# Generated by Django 5.0 on 2023-12-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_cover_color_remove_item_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.covercolor'),
        ),
        migrations.AddField(
            model_name='item',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.format'),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.language'),
        ),
        migrations.AddField(
            model_name='item',
            name='number_of_pages',
            field=models.FloatField(default=0.0),
        ),
    ]
