# Generated by Django 5.0 on 2023-12-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_cover_color_item_format_item_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.covercolor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.format'),
        ),
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.language'),
        ),
    ]
