# Generated by Django 5.0 on 2023-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_cover_color_alter_item_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
