# Generated by Django 5.0 on 2024-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_rename_name_item_title_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
