# Generated by Django 5.0 on 2024-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
